AWSTemplateFormatVersion: 2010-09-09
Description: CI/CD pipeline for github projects
Parameters:
  GitHubOwner:
    Type: String
    AllowedPattern: '[A-Za-z0-9-]+'
    Default: somveergithub
  GitHubRepository:
    Type: String
    AllowedPattern: '[A-Za-z0-9-]+'
  GitHubBranch:
    Type: String
    AllowedPattern: '[A-Za-z0-9-]+'
    Default: main
  TemplatePath:
    Type: String
    Default: template.yml
  ParametersFile:
    Type: String
    Default: params.json
Resources:
  CodeBuildSourceCredential:
    Type: 'AWS::CodeBuild::SourceCredential'
    Properties:
      AuthType: PERSONAL_ACCESS_TOKEN
      ServerType: GITHUB
      Token: '{{resolve:secretsmanager:gitpat:SecretString:GitPAT}}'

  CodeBuildProject:
    Type: 'AWS::CodeBuild::Project'
    Properties:
      Name: !Ref 'AWS::StackName'
      ServiceRole: !GetAtt CodePipelineServiceRole.Arn
      Source:
        Type: GITHUB
        Location: !Sub 'https://github.com/${GitHubOwner}/${GitHubRepository}.git'
        BuildSpec: buildspec.yaml
        Auth:
          Type: OAUTH
          Resource: !Ref CodeBuildSourceCredential
      Artifacts:
        Type: NO_ARTIFACTS
      Triggers:
        Webhook: true
        FilterGroups:
          - - Type: EVENT
              Pattern: >-
                PULL_REQUEST_CREATED, PULL_REQUEST_UPDATED,
                PULL_REQUEST_REOPENED
            - Type: BASE_REF
              Pattern: !Sub '^refs/heads/${GitHubBranch}$'
      Environment:
        Type: LINUX_CONTAINER
        ComputeType: BUILD_GENERAL1_SMALL
        Image: 'aws/codebuild/standard:4.0'

  CodePipelineServiceRole:
    Type: 'AWS::IAM::Role'
    Properties:
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - codepipeline.amazonaws.com
                - cloudformation.amazonaws.com
                - codebuild.amazonaws.com
            Action: 'sts:AssumeRole'
      Policies:
        - PolicyName: root
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              - Sid: CodeBuildAccessPolicy
                Effect: Allow
                Action:
                  - 'codebuild:*'
                  - 'logs:*'
                  - 's3:*'
                  - 'cloudformation:*'
                Resource: '*'

  CodePipelineArtifactStore:
    Type: 'AWS::S3::Bucket'
    Properties:
      BucketName: !Sub 'codepipeline-${GitHubRepository}'
      VersioningConfiguration:
        Status: Enabled

  CodePipelineWebhook:
    Type: 'AWS::CodePipeline::Webhook'
    Properties:
      Authentication: GITHUB_HMAC
      AuthenticationConfiguration:
        SecretToken: '{{resolve:secretsmanager:gitpat:SecretString:GitPAT}}'
      RegisterWithThirdParty: 'true'
      Filters:
        - JsonPath: $.ref
          MatchEquals: 'refs/heads/{Branch}'
        - JsonPath: $.repository.name
          MatchEquals: '{Repo}'
      TargetPipeline: !Ref CodePipeline
      TargetAction: GitHubSourceAction
      TargetPipelineVersion: !GetAtt CodePipeline.Version

  CodePipeline:
    Type: 'AWS::CodePipeline::Pipeline'
    Properties:
      Name: !Ref 'AWS::StackName'
      RoleArn: !GetAtt CodePipelineServiceRole.Arn
      ArtifactStore:
        Type: S3
        Location: !Ref CodePipelineArtifactStore
      Stages:
        - Name: Get-Source
          Actions:
            - Name: GitHubSourceAction
              ActionTypeId:
                Category: Source
                Owner: ThirdParty
                Version: 1
                Provider: GitHub
              Configuration:
                Owner: !Ref GitHubOwner
                Repo: !Ref GitHubRepository
                Branch: !Ref GitHubBranch
                PollForSourceChanges: false
                OAuthToken: '{{resolve:secretsmanager:gitpat:SecretString:GitPAT}}'
              OutputArtifacts:
                - Name: SourceOutput
              RunOrder: 1

        - Name: Build-Test
          Actions:
            - Name: BuildTest
              ActionTypeId:
                Category: Build
                Owner: AWS
                Provider: CodeBuild
                Version: '1'
              Configuration:
                ProjectName: !Ref CodeBuildProject
              OutputArtifacts:
                - Name: !Sub '${AWS::StackName}-Build'
              InputArtifacts:
                - Name: SourceOutput
              RunOrder: 1
        - Name: Deploy-Stack
          Actions:
            - Name: ReplaceChangeSet
              ActionTypeId:
                Category: Deploy
                Owner: AWS
                Version: '1'
                Provider: CloudFormation
              InputArtifacts:
                - Name: !Sub '${AWS::StackName}-Build'
              Configuration:
                ActionMode: CHANGE_SET_REPLACE
                StackName: !Sub '${AWS::StackName}-deployment'
                ChangeSetName: !Sub '${AWS::StackName}-deployment'
                TemplatePath: !Sub '${AWS::StackName}-Build::${TemplatePath}'
                TemplateConfiguration: '${AWS::StackName}-Build::${ParametersFile}'
                RoleArn: !GetAtt CodePipelineServiceRole.Arn
              RunOrder: 1
            - Name: ExecuteChangeSet
              ActionTypeId:
                Category: Deploy
                Owner: AWS
                Version: '1'
                Provider: CloudFormation
              Configuration:
                ActionMode: CHANGE_SET_EXECUTE
                StackName: !Sub '${AWS::StackName}-deployment'
                ChangeSetName: !Sub '${AWS::StackName}-deployment'
              RunOrder: 2
