AWSTemplateFormatVersion: 2010-09-09
Description: CI/CD pipeline for github projects

Parameters:
  GitHubOwner:
    Type: String
    AllowedPattern: "[A-Za-z0-9-]+"
    Default: somveergithub

  GitHubRepository:
    Type: String
    AllowedPattern: "[A-Za-z0-9-]+"
  
  GitHubBranch:
    Type: String
    AllowedPattern: "[A-Za-z0-9-]+"
    Default: main
Resources:
  CodeBuildServiceRole:
    Type: 'AWS::IAM::Role'
    Properties:
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              Service: codebuild.amazonaws.com
            Action: 'sts:AssumeRole'
      Policies:
        - PolicyName: root
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              - Sid: CodeBuildAccessPolicy
                Effect: Allow
                Action:
                  - 'codebuild:*'
                Resource: '*'
              - Sid: CloudWatchLogsAccessPolicy
                Effect: Allow
                Action:
                  - 'logs:FilterLogEvents'
                  - 'logs:GetLogEvents'
                Resource: '*'
              - Sid: S3AccessPolicy
                Effect: Allow
                Action:
                  - 's3:CreateBucket'
                  - 's3:GetObject'
                  - 's3:List*'
                  - 's3:PutObject'
                  - 's3:GetObject*'
                Resource: '*'
              - Sid: S3BucketIdentity
                Effect: Allow
                Action:
                  - 's3:GetBucketAcl'
                  - 's3:GetBucketLocation'
                Resource: '*'
  CodeBuildSourceCredential:
    Type: AWS::CodeBuild::SourceCredential
    Properties:
        AuthType: PERSONAL_ACCESS_TOKEN
        ServerType: GITHUB
        Token: "{{resolve:secretsmanager:gitpat:SecretString:GitPAT}}"

        
  CodeBuildProject:
    Type: 'AWS::CodeBuild::Project'
    Properties:
      Name: !Ref 'AWS::StackName'
      ServiceRole: !GetAtt CodeBuildServiceRole.Arn
      Source:
        Type: GITHUB
        Location: !Sub https://github.com/${GitHubOwner}/${GitHubRepository}.git
        BuildSpec: buildspec.yaml
        Auth:
            Type: OAUTH
            Resource: !Ref CodeBuildSourceCredential
      Artifacts:
        Type: NO_ARTIFACTS
      Triggers:
        Webhook: true
        FilterGroups:
            - - Type: EVENT
                Pattern: PULL_REQUEST_CREATED, PULL_REQUEST_UPDATED, PULL_REQUEST_REOPENED
              - Type: BASE_REF
                Pattern: !Sub ^refs/heads/${GitHubBranch}$
      Environment:
        Type: LINUX_CONTAINER
        ComputeType: BUILD_GENERAL1_SMALL
        Image: aws/codebuild/standard:4.0